Author: Robert Guthrie. This notebook can also be found here: https://github.com/pytorch/tutorials/blob/master/beginner_source/nlp/pytorch_tutorial.py

In [1]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


# Creating Tensors
Tensors can be created from Python lists with the torch.tensor()
function.


In [5]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [6]:
# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.tensor(M_data)
print(M)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [7]:
# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])



What is a 3D tensor anyway? Think about it like this. If you have a
vector, indexing into the vector gives you a scalar. If you have a
matrix, indexing into the matrix gives you a vector. If you have a 3D
tensor, then indexing into the tensor gives you a matrix!

A note on terminology:
when I say "tensor" in this tutorial, it refers
to any torch.Tensor object. Matrices and vectors are special cases of
torch.Tensors, where their dimension is 1 and 2 respectively. When I am
talking about 3D tensors, I will explicitly use the term "3D tensor".


In [8]:
# Index into V and get a scalar (0 dimensional tensor)
print(V[0])
# Get a Python number from it
print(V[0].item())

tensor(1.)
1.0


In [9]:
# Index into M and get a vector
print(M[0])

tensor([1., 2., 3.])


In [10]:
# Index into T and get a matrix
print(T[0])

tensor([[1., 2.],
        [3., 4.]])


You can also create tensors of other data types. To create a tensor of integer types, try
torch.tensor([[1, 2], [3, 4]]) (where all elements in the list are integers).
You can also specify a data type by passing in ``dtype=torch.data_type``.
Check the documentation for more data types, but
Float and Long will be the most common.



You can create a tensor with random data and the supplied dimensionality
with torch.randn()


In [11]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[ 0.9933,  0.8695,  1.8381,  2.0946, -0.6188],
         [ 0.5355,  2.4298, -1.2984,  1.2087,  0.1467],
         [-0.1710, -2.2120, -0.3667,  0.8402,  0.1421],
         [ 0.7022,  0.0724, -0.1284, -0.3544,  0.7491]],

        [[-0.8267,  1.0836,  1.7921,  0.7837,  1.4362],
         [ 0.3063, -0.4216,  0.0503, -0.8791,  0.3393],
         [-1.6931,  2.4043, -1.7740,  1.5800,  0.9444],
         [-1.5097, -0.0590, -0.5988, -1.1768,  0.2954]],

        [[-0.3387,  0.1746, -0.6634,  1.2895,  1.5676],
         [-0.4770,  0.6921, -0.5447, -1.8883,  0.0301],
         [ 0.6223,  2.4160, -0.5847, -1.8492,  0.0858],
         [-0.5276, -1.9525, -0.3548,  1.7657,  0.3555]]])


# Operations with Tensors

You can operate on tensors in the ways you would expect.

In [12]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])



See `the documentation <https://pytorch.org/docs/torch.html>`__ for a
complete list of the massive number of operations available to you. They
expand beyond just mathematical operations.

One helpful operation that we will make use of later is concatenation.


In [13]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

tensor([[-0.0268, -0.0120,  0.7167, -0.4832,  1.2191],
        [-0.8627, -0.8733,  1.0536,  0.3487,  1.4612],
        [ 0.6162,  0.1261, -2.7631, -0.8861, -0.6191],
        [-0.3392, -0.0728,  0.6785, -1.6947, -1.1593],
        [-0.6923,  1.0877,  0.8936, -0.3788, -0.7710]])


In [14]:
# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

tensor([[-0.3395,  0.3950,  0.3896, -1.2925, -0.9866,  0.6381,  0.0344,  0.9727],
        [-2.0338,  0.6689, -1.4960,  1.6786, -0.6180,  0.4148, -0.5320,  1.5094]])


If your tensors are not compatible, torch will complain.  Uncomment to see the error
torch.cat([x_1, x_2])


# Reshaping Tensors
Use the .view() method to reshape a tensor. This method receives heavy
use, because many neural network components expect their inputs to have
a certain shape. Often you will need to reshape before passing your data
to the component.


In [15]:
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))  # Reshape to 2 rows, 12 columns
# Same as above.  If one of the dimensions is -1, its size can be inferred
print(x.view(2, -1))

tensor([[[-1.0081,  0.3256, -1.0379,  0.1090],
         [ 2.2235, -1.8049, -0.0740,  2.0850],
         [ 1.5283,  1.2265,  0.3327, -1.7070]],

        [[-1.1354,  0.0862,  1.2060, -0.3851],
         [-1.0151, -0.5068, -0.9745,  0.3149],
         [-0.1150, -0.1721,  0.2105, -0.8166]]])
tensor([[-1.0081,  0.3256, -1.0379,  0.1090,  2.2235, -1.8049, -0.0740,  2.0850,
          1.5283,  1.2265,  0.3327, -1.7070],
        [-1.1354,  0.0862,  1.2060, -0.3851, -1.0151, -0.5068, -0.9745,  0.3149,
         -0.1150, -0.1721,  0.2105, -0.8166]])
tensor([[-1.0081,  0.3256, -1.0379,  0.1090,  2.2235, -1.8049, -0.0740,  2.0850,
          1.5283,  1.2265,  0.3327, -1.7070],
        [-1.1354,  0.0862,  1.2060, -0.3851, -1.0151, -0.5068, -0.9745,  0.3149,
         -0.1150, -0.1721,  0.2105, -0.8166]])



Computation Graphs and Automatic Differentiation
================================================

The concept of a computation graph is essential to efficient deep
learning programming, because it allows you to not have to write the
back propagation gradients yourself. A computation graph is simply a
specification of how your data is combined to give you the output. Since
the graph totally specifies what parameters were involved with which
operations, it contains enough information to compute derivatives. This
probably sounds vague, so let's see what is going on using the
fundamental flag ``requires_grad``.

First, think from a programmers perspective. What is stored in the
torch.Tensor objects we were creating above? Obviously the data and the
shape, and maybe a few other things. But when we added two tensors
together, we got an output tensor. All this output tensor knows is its
data and shape. It has no idea that it was the sum of two other tensors
(it could have been read in from a file, it could be the result of some
other operation, etc.)

If ``requires_grad=True``, the Tensor object keeps track of how it was
created. Lets see it in action.


In [18]:
# Tensor factory methods have a ``requires_grad`` flag
x = torch.tensor([1., 2., 3.], requires_grad=True)

In [19]:
# With requires_grad=True, you can still do all the operations you previously
# could
y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x + y
print(z)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [20]:
# BUT z knows something extra.
print(z.grad_fn)

So Tensors know what created them. z knows that it wasn't read in from
a file, it wasn't the result of a multiplication or exponential or
whatever. And if you keep following z.grad_fn, you will find yourself at
x and y.

But how does that help us compute a gradient?


In [21]:
# Lets sum up all the entries in z
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


So now, what is the derivative of this sum with respect to the first
component of x? In math, we want

$$   \frac{\partial s}{\partial x_0} $$



Well, s knows that it was created as a sum of the tensor z. z knows
that it was the sum x + y. So

$$s = \overbrace{x_0 + y_0}^\text{$z_0$} + \overbrace{x_1 + y_1}^\text{$z_1$} + \overbrace{x_2 + y_2}^\text{$z_2$}$$

And so s contains enough information to determine that the derivative
we want is 1!

Of course this glosses over the challenge of how to actually compute
that derivative. The point here is that s is carrying along enough
information that it is possible to compute it. In reality, the
developers of Pytorch program the sum() and + operations to know how to
compute their gradients, and run the back propagation algorithm. An
in-depth discussion of that algorithm is beyond the scope of this
tutorial.



Lets have Pytorch compute the gradient, and see that we were right:
(note if you run this block multiple times, the gradient will increment.
That is because Pytorch *accumulates* the gradient into the .grad
property, since for many models this is very convenient.)


In [22]:
# calling .backward() on any variable will run backprop, starting from it.
s.backward()
print(x.grad)

tensor([1., 1., 1.])



Understanding what is going on in the block below is crucial for being a
successful programmer in deep learning.


In [23]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)
# By default, user created Tensors have ``requires_grad=False``
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)

False False
None


In [24]:
# ``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
# flag in-place. The input flag defaults to ``True`` if not given.
x = x.requires_grad_()
y = y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)

True


In [25]:
# Now z has the computation history that relates itself to x and y
# Can we just take its values, and **detach** it from its history?
new_z = z.detach()

In [26]:
# ... does new_z have information to backprop to x and y?
# NO!
print(new_z.grad_fn)
# And how could it? ``z.detach()`` returns a tensor that shares the same storage
# as ``z``, but with the computation history forgotten. It doesn't know anything
# about how it was computed.
# In essence, we have broken the Tensor away from its past history

None



You can also stop autograd from tracking history on Tensors
with ``.requires_grad=True`` by wrapping the code block in
``with torch.no_grad():``

In [27]:

print(x.requires_grad)
print((x ** 2).requires_grad)

True
True


In [28]:
with torch.no_grad():
	print((x ** 2).requires_grad)

False
